name: Update Site after weekend

on:
  workflow_dispatch: 
  push:
    branches: [ "main" ]

permissions: 
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Action to check out your repository code

    - name: Set up Python
      uses: actions/setup-python@v5 # Action to set up a Python environment
      with:
        python-version: '3.14' # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f src/requirements.txt ]; then pip install -r src/requirements.txt; fi # Installs packages from requirements.txt if present

    - name: Execute Python script
      run: | 
        python3 src/update_tables.py # Runs your Python script using the 'python' command
    - name: Execute Python script
      run: | 
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add docs
        git commit -m "Auto-Update Site"
        git push
